### ISSUE TITLE
Pynguin crashes while trying to replicate results

### ISSUE THREAD

**Issue by rakshithshenoy** [microsoft/codamosa#20]
I have followed the instructions given in the replication folder's README and the installation of all the test-apps happens successfully. However, as soon as I try to execute the run_one.sh script, the container gets created and Pynguin starts up but it crashes instantly. Is there any way this can be fixed? The output I'm getting has been attached below - 
![image](https://github.com/microsoft/codamosa/assets/49361039/f68d501e-299b-4741-a65c-98be6df3b073)
![image](https://github.com/microsoft/codamosa/assets/49361039/271acd33-a0dd-4d57-8397-1b2968c50230)

**Comment by carolemieux** [comment]
This is a Pynguin issue, not a codamosa one. It looks like you are using the DynaMOSA algorithm with Branch + Line coverage, and DynaMOSA can't run with Line Coverage in this version of Pynguin. Try specifying --algorithm MOSA, or remove Line coverage from the coverage args. 


Let me know if this resolves the issue.

**Comment by rakshithshenoy** [comment]
Explicitly specifying the algorithm as MOSA stopped the issue of Pynguin crashing, however, the codex API calls are not being made. When I try to run it for any module, it just gives the default Pynguin output. In order for the codex call to be made, is there any additional change that should be made to the run_one.sh script?

**Comment by carolemieux** [comment]
Ah, yes, in that case, you want --algorithm CODAMOSA  :)

I think this is the effect of a bug in the run_one.sh script which is eventually going to be fixed by PR #14 . Essentially the args from ARGFILE are not being passed in.

You should be able to patch run_one.sh with:
https://github.com/microsoft/codamosa/pull/14/commits/9457c1cc97e3380e388ae4f37b369be4522a9594


Let me know if that resolves the issue locally; I'll leave this issue open until #14 is merged

**Comment by carolemieux** [comment]
Are you still seeing the issue? It should be resolved now.

**Comment by rakshithshenoy** [comment]
Hi, I had added the changes from that PR following which an attempt to send the request to CODEX was being made. However, I think the model code-davinci-002 is available only to research scholars and so the attempt kept failing as I don't have access to it.

**Comment by carolemieux** [comment]
Indeed, code-davinci-002 is no longer available. You will need to use a different OpenAI model. I have updated the READMEs to note this fact. Please reopen if there are additional issues.
