### ISSUE TITLE
What's "test-apps/" ?

### ISSUE THREAD

**Issue by SmokeyDays** [microsoft/codamosa#5]
I tried to reproduce your results using the instructions in the `README.md` file in the `replication/` directory, but I encountered the following problem: 
`/scripts/setup_test_apps.sh: line 6: cd: test-apps: No such file or directory`
Upon reviewing your scripts, I noticed that you test the code by running it in a Docker container with files located in `replication/test-apps/`. However, this directory does not exist in your GitHub project. Could you please provide guidance on what files I should put in this directory and in what format?

**Comment by carolemieux** [comment]
Can you please specify which command you ran which led to the error message? It is possible there is a typo somewhere in the scripts

You will need to follow the setup instructions here: https://github.com/microsoft/codamosa/tree/main/replication#start-the-benchmark-container to populate the `test-apps` subdirectory properly. This directory will then contain the source code for the projects we pull benchmarks from; we are not distributing that source code directly.

**Comment by SmokeyDays** [comment]
Well, this instruction never told me how to populate the test-apps directory, and that is exactly what I am most confused about.
For me, I just clone this repository, and run ``sudo bash replication/scripts/start_benchmark_container.sh `` command. Did I miss any steps? What else should I do?

**Comment by carolemieux** [comment]
Did you load the docker container as well, as outlined above that instruction?

If not, do that first.

If so, try creating an empty directory named test-apps in the location where you will run the script. I thought the docker command should create it automatically, but it is possible it does not. I will fix the script accordingly if so.

The script bind mounts a directory in the docker container to a local 'test-apps' directory, and does all the population of that directory in docker. So you should not need to do anything more than create the empty directory and run the script.

If this does not work, please provide the system you are running on (OS and docker version) and all the commands run so I can better debug.

**Comment by SmokeyDays** [comment]
Thanks, that works! After I created a test-apps/ folder manually, I ran the script, and got permisson denied. Then I tried to edit the ``start_benchmark_container.sh`` script, to ``docker run --user=root``, and then it starts work.

**Comment by claudeyj** [comment]
> Thanks, that works! After I created a test-apps/ folder manually, I ran the script, and got permisson denied. Then I tried to edit the `start_benchmark_container.sh` script, to `docker run --user=root`, and then it starts work.

Yes, I also agree that it would be better that more clarification be added so that users won't get stuck here.

**Comment by carolemieux** [comment]
I have in [d06a384](https://github.com/microsoft/codamosa/commit/d06a384ea9b86e8e1792354fd4557ba36fe5a6d6) updated the scripts to automatically create the test-apps directory, as well as a disclaimer about the need to add your user to the docker group/add --user=root/sudo the commands. Feel free to reopen the issue if problems persist.
