### ISSUE TITLE
replication/scripts/run_one.sh script support for replaying

### ISSUE THREAD

**Issue by claudeyj** [microsoft/codamosa#7]
Currently the command in run_one.sh script is
```
CMD="docker run --rm -v ${TEST_DIR}:/input:ro -v ${OUT_DIR}:/output -v ${TEST_DIR}:/package:ro pynguin-runner --assertion-generation NONE --project_path /input --module-name ${TEST_MOD} --output-path /output --maximum_search_time $SEARCH_TIME --output_variables TargetModule,Coverage,BranchCoverage,LineCoverage,ParsedStatements,UninterpStatements,ParsableStatements,LLMCalls,LLMQueryTime,LLMStageSavedTests,LLMStageSavedMutants,LLMNeededExpansion,LLMNeededUninterpreted,LLMNeededUninterpretedCallsOnly,RandomSeed,AccessibleObjectsUnderTest,CodeObjects,CoverageTimeline --report-dir /output --coverage_metrics BRANCH,LINE $ARGS --authorization-key $AUTH_KEY -v"
```
But if we want to replay the test generation we should replace `--authorization-key $AUTH_KEY` with a path of a file that contains '--replay-generation-from-file /output/codex_generations.py'. So a possible approach to fix this is to denote this config as a whole e.g., $AUTH_PATH (the path of a file that contains either `--authorization-key <openai_key>` or  `--replay-generation-from-file /output/codex_generations.py`).

**Comment by carolemieux** [comment]
Perhaps a neater solution would be to add some proper command line options to `run_one.sh` that dispatch between these two modes, e.g. `run_one.sh --auth` or `run_one.sh --replay`. Then the user would not be required  to specify the whole (wordy) CodaMOSA command-line options. 

I can implement, but any thoughts on what would make this easiest to use? One options would be to  specify the auth key/generation file contents on command line like  `run_one.sh --auth SECRET_AUTH_KEY` or `run_one.sh --replay /output/codex_generations.py`. The current interface has that information contained in a file instead.

**Comment by claudeyj** [comment]
> Perhaps a neater solution would be to add some proper command line options to `run_one.sh` that dispatch between these two modes, e.g. `run_one.sh --auth` or `run_one.sh --replay`. Then the user would not be required to specify the whole (wordy) CodaMOSA command-line options.
> 
> I can implement, but any thoughts on what would make this easiest to use? One options would be to specify the auth key/generation file contents on command line like `run_one.sh --auth SECRET_AUTH_KEY` or `run_one.sh --replay /output/codex_generations.py`. The current interface has that information contained in a file instead.

I prefer the later one. It's more straightforward to me.

**Comment by carolemieux** [comment]
Just to make clear because I always confuse former/latter, you mean to say you prefer an interface like `run_one.sh --auth SECRET_AUTH_KEY or run_one.sh --replay /output/codex_generations.py`

**Comment by claudeyj** [comment]
Oh sorry, yes I think I prefer an interface like `run_one.sh --auth SECRET_AUTH_KEY` or `run_one.sh --replay /output/codex_generations.py` rather than `run_one.sh --auth` or `run_one.sh --replay`.

**Comment by carolemieux** [comment]
Sounds good. I will try to update the script in the next week, or feel free to make a PR with the changes if I am too slow, and I will review.

**Comment by claudeyj** [comment]
Thank you, I can create a PR if you don't mind.

**Comment by claudeyj** [comment]
Since OpenAI will not support Codex very soon, maybe CodaMosa can only support replay mode. So maybe I should only implement that interface?
