### ISSUE TITLE
Docker build issues

### ISSUE THREAD

**Issue by dasong-sd** [microsoft/codamosa#9]
Hi, 

As suggested in README, I tried to build the Dockerfile which is in the repository. 

`docker build -t codamosa-runner -f docker/Dockerfile --platform linux/arm64 .`

However, this does not work. I saw an error related to poetry build.

<img width="1920" alt="Screenshot 2023-04-17 at 10 36 39 AM" src="https://user-images.githubusercontent.com/79809505/232552517-5eb29bf3-4202-40f9-8500-1c2d7d689be4.png">

I started debugging this issue and I tried several ways including changing the file structure as the following.
```
codamosa
│   ...
│
└───src
│   │   pynguin
│   ...
```
Meanwhile, I change the project name to pynguin in `pyproject.toml`. And run `docker build -t codamosa-runner -f docker/Dockerfile --platform linux/arm64 .` again. Although the above error didn't show again, a new error relating to the pynguin source file showed up.

<img width="1903" alt="Screenshot 2023-04-17 at 10 43 37 AM" src="https://user-images.githubusercontent.com/79809505/232553901-d13057a8-e846-435f-8903-e49b1978599d.png">

I also tried to build a docker from pynguin repo directly. It works well. I would like to ask for your help first before trying to migrate codamosa to the newest pynguin version.

Could you please help me with that? 

Thank you,
Da

**Comment by carolemieux** [comment]
Apologies for the long response time.

Can you check whether updating the pyproject.toml file in the manner as in this patch: https://github.com/microsoft/codamosa/pull/10/commits/0d78d06d06c635f37b21bbfb9876e6b8da5b6a3e (set name to pynguin, version to "0.19.0") resolves the issue? If so, I will merge the change into main.

**Comment by dasong-sd** [comment]
Yes, this update resolves the building issue. Thank you! :)
